### ISSUE TITLE
Add S3 destination to na_elementsw_backup module

### ISSUE THREAD

**Issue by scaleoutsean** [ansible-collections/netapp.elementsw#1]
##### SUMMARY

- There appears to be no S3-related inputs for this module as of mid 2021, so it seems like only SF to SF backups are supported.
- `snapshot_id` param could be added

##### ISSUE TYPE

One of two backup destinations is supported - S3/Swift (okay, nobody uses Swift) is not yet, and it requires slightly different input parameters from what is currently available so it appears that the current module cannot work with Backup to S3.

![image](https://user-images.githubusercontent.com/16622642/122709816-9b264700-d291-11eb-9b85-79b3fae4fea3.png)

Notice how [the API](https://solidfire-sdk-python.readthedocs.io/en/latest/solidfire.html#solidfire.models.StartBulkVolumeReadRequest) allows the useful `snapshot_id` param which isn't currently available or exposed in the UI. That could be added both here and to existing (SF to SF) module. 

TFM says if `snapshot_id = 0`, then ad-hoc snapshot is made, but `snapshot_id = ""` is effectively the same, that's why the current module works fine without it.

##### COMPONENT NAME

-  na_elementsw_backup module

##### ADDITIONAL INFORMATION

```yaml
- name: example netapp solidfire
  hosts: localsf
  gather_facts: no
  connection: local

  tasks:  
    - name: SolidFire backup to S3 
      na_elementsw_backup:
        hostname: "http://s3.com.org:18443"
        src_volume_id: "{{ item }}"
        dest_hostname: "{{ s3_hostname }}"
        dest_username: "{{ s3_bucket }}"
        dest_s3_access_key: "{{ s3_keya }}"
        dest_s3_secret_key: "{{ s3_keys }}"
        dest_s3_destination_bucket: "backups"
        dest_s3_tags: ["monday","snap"]
        format: native
      loop:
        - 1 
        - 2
```
